# Generated by Django 2.2.6 on 2021-08-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20210813_0105"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
    ]
