# Generated by Django 2.2.6 on 2021-08-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_auto_20210815_2335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, следует ли считать этого пользователя активным. ",
                verbose_name="активный",
            ),
        ),
    ]
