# Generated by Django 2.2.6 on 2021-08-16 17:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_auto_20210816_0012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="комментарии конкретного автора",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.Review",
                verbose_name="комментарии конкретного ревью",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ревью конкретного автора",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="оценка произведения",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Текст ревью"),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.Title",
                verbose_name="ревью конкретного произведения",
            ),
        ),
    ]
