# Generated by Django 2.2.6 on 2021-08-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_auto_20210816_1723"),
        ("reviews", "0007_auto_20210816_0059"),
    ]

    operations = []
