# Generated by Django 2.2.6 on 2021-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_auto_20210816_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Определяет, следует ли считать этого пользователя активным.",
                verbose_name="активный",
            ),
        ),
    ]
