# Generated by Django 2.2.6 on 2021-08-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_auto_20210817_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, следует ли считать этого пользователя активным.",
                verbose_name="активный",
            ),
        ),
    ]
