# Generated by Django 2.2.6 on 2021-08-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0012_auto_20210817_1800"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["name"],
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={
                "verbose_name": "произведение",
                "verbose_name_plural": "произведения",
            },
        ),
    ]
